---
title: "02_clean"
format: html
editor: visual
---

## Load libraries

```{r}
#| label: "load-libraries" 
#| echo: TRUE
#| eval: TRUE 
#| output: FALSE  

library("tidyverse")
library("table1")
library("here")
```

## Load dataset

```{r}
#| label: "load-data" 

expression_meta_data_clean <- read_tsv(file = here("data/03_expression_meta_data_load.tsv.gz"))


```

### Cleaning data

First we choose the wanted columns to work with in the wanted order and rename them:

```{r}
#| label: "choosing-columns"

expression_meta_data_clean_1 <- expression_meta_data_clean |> 
  select(sample_id = sample,
         gender = gender.demographic,
         race = race.demographic,
         vital_status = vital_status.demographic,
         overall_survival = OS,
         primary_site,
         pathologic_stage = ajcc_pathologic_stage.diagnoses,
         age_at_index = age_at_index.demographic,
         year_of_birth = year_of_birth.demographic,
         year_of_death = year_of_death.demographic,
         tissue_source_location = name.tissue_source_site,
         cigarettes_per_day = cigarettes_per_day.exposures,
         years_smoked = years_smoked.exposures,
         alcohol_history = alcohol_history.exposures,
         peptide_target,
         expression)
```

Then we trim the sample_ID to not contain the code TCGA standing for The Cancer Genome Atlas, as all the values comes from this data and has this code in the beginning.

```{r}
#| label: "modify-sample-id"

# Modify the sample_id column
expression_meta_data_clean_2 <- expression_meta_data_clean_1 |> 
  mutate(
    
# Keep only the last part in sample_id and leave out TCGA-XX
    sample_id = sub("^TCGA-(.*)", "\\1", sample_id)
    
  )
```

## Write the clean dataset to a tsv.gz file

```{r}
#| label: "write-clean-data-to-tsv.gz"

data_dir <- here("data/")


write_tsv( x = expression_meta_data_clean_2,
           file = str_c(data_dir, 
                  "04_expression_meta_data_clean.tsv.gz"))


```
