---
title: "04_describe"
author:
- "Asta Zeuner - s203544 - azeuner"
- "Astrid Ginnerup - s203523 - AGinnerup"
- "Emma Danø - s203564 - EDanoe"
- "Andrea Kristensen - s193769 - AndreaMTK"
- "Yayi Wang - s243554 - Yayi0117"
  html: 
    embed-resources: true
execute: 
  message: FALSE
  warning: FALSE
---

## Loading the data

```{r}
#| label: "load-data" 

expression_meta_data_load<- read_tsv(file = here("data/03_expression_meta_data_load.tsv.gz"))

expression_meta_data_clean <- read_tsv(file = here("data/04_expression_meta_data_clean.tsv.gz"))

expression_meta_data_aug <- read_tsv(file = here("data/04_expression_meta_data_aug.tsv.gz"))


```

## Load Library

```{r}
#| label: "load-libraries" 
#| echo: TRUE
#| eval: TRUE 
#| output: FALSE  

library("tidyverse")

```

## Discription

-   how many patients

```{r}
expression_meta_data_aug |>
  select(patient_id) |>
  n_distinct()
```

-   could compare with the original data before cleaning

```{r}
expression_meta_data_load |>
  select(submitter_id) |>
  n_distinct()

```

Check what different pathologic stages there are:

```{r}
# Count occurrences of pathologic_stages per patient_id
expression_meta_trimmed |> 
  group_by(pathologic_stage) |> 
  summarize(count = n(), .groups = "drop")  # Count the occurrences and ungroup
```

-   Check the lowest and highest age

```{r}
expression_meta_data_aug |> 
  summarize(
    min_age = min(age_at_index, na.rm = TRUE), # Lowest age
    max_age = max(age_at_index, na.rm = TRUE)  # Highest age
  )
```

-   Check how many peptides

```{r}
n_peptides <- expression_meta_data_aug |>
  select(peptide_target) |>
  n_distinct()

n_peptides
```
