---
title: "07_analysis_3"
author:
- "Asta Zeuner - s203544 - azeuner"
- "Astrid Ginnerup - s203523 - AGinnerup"
- "Emma Danø - s203564 - EDanoe"
- "Andrea Kristensen - s193769 - AndreaMTK"
- "Yayi Wang - s243554 - Yayi0117"
html: 
    embed-resources: true
execute: 
  message: FALSE
  warning: FALSE
---

-   make some descriptive plots eg. facet wrap

-   survival vs alcohol and smoking

-   vital_status vs tissue_source_location

-   ethnicity

-   gender overall survival

## **Loading libraries**

```{r}
#| label: "load-libraries" 
#| echo: TRUE
#| eval: TRUE 
#| output: FALSE  
#| 
library("ggplot2")
#library("colorspace")
```

Loading data

```{r}
#| label: "load-data" 

expression_meta_data_aug <- read_tsv(file = here("data/04_expression_meta_data_aug.tsv.gz"))

```

## Plot with gender and overall survival

add absolute numbers

change axis titles from count

```{r}

gender_totals <- expression_meta_data_aug |> 
  group_by(gender, vital_status) |> 
  summarize(total = n(), .group = "drop")


ggplot(data = expression_meta_data_aug,
       mapping = aes(x = gender,
                     fill = vital_status
                     ))+
  
  geom_bar(color = "powderblue",
           position = "fill")+
  
  
  geom_text(data = gender_totals, 
            aes(x = gender, 
                y = 0.1,  # Slightly higher than the top of the bars
                label = paste("Total: ", total)),
            position = position_stack(vjust = 0.5), 
            inherit.aes = FALSE,
            size = 2,   # Adjust text size
            color = "black")+
  
  
  scale_fill_brewer(palette = "Pastel2")+
  labs(x = "Gender", 
       y = "Proportion",
       title = "Distribution of Gender and Vital Status",
       subtitle = "Proportional representation by gender and race",
       fill = "Vital Status"
       )+
  
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        legend.position = "right"
        )
  

#ggsave("~/projects/group_21_project/doc/images/Barplot_VitalStatusGenders.png", plot= last_plot())



#trying to add absolute numbers
#geom_text(data = gender_totals,
            #aes(x = gender, 
                #y= 0.2, 
                #label = total),
            #position = position_stack(vjust=0.5),
            #inherit.aes = FALSE,
            #vjust = 1)+



```

Facet wrap with ethnicity and survival

add absolute values

```{r}
ggplot(data = expression_meta_data_aug,
       mapping = aes(x = gender,
                     fill = vital_status
                     ))+
  geom_bar(color = "powderblue",
           position = "fill"
           )+
  scale_fill_brewer(palette = "Pastel2")+
  facet_wrap(~race)+
  labs(x = "Gender", 
       y = "Proportion",
       title = "Distribution of Gender and Vital Status Across Races",
          subtitle = "Proportional representation by gender and race",
       fill = "Vital Status") +
  
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.text = element_text(size = 6, face = "bold"))

```

```{r}

expression_meta_data_aug |> 
  drop_na(pathologic_stage) |> 
ggplot(mapping = aes(x = vital_status,
                     y = cigarettes_per_day))+
geom_boxplot(color = "lawngreen",
             fill = "seagreen3")+
  facet_wrap(~pathologic_stage)+
  labs(x = "Vital Status", 
       y = "Cigarettes per day",
       title = "Distribution of Cigarettes per day and Vital Status Across pathological stages",
       fill = "Vital Status")+
  theme(plot.title = element_text(size = 10, hjust = 0.5))

```
